### ISSUE TITLE
Spojovaci matky

### ISSUE THREAD

**Issue by syky27** [3DprintFIT/B171HW-TabletBarMount-Assignment#11]
Je potreba je prendat na spodni stranu spodni casti modelu, s dirami skrz takhle nic nedrzi....

**Comment by hroncok** [comment]
Předpokládal jsem, že je tam nalepíš/vtavíš, aby tam držely, ale ano, je to asi blbost.

Problém je, že pokud je dáš dolů, potřebuješ mít info i o šířce šroubu.

**Comment by syky27** [comment]
To tam je stejne na ty diry co jsou v horni casti, ty matky se vytrhnout pouzivanim kdyz budou nahore...

**Comment by hroncok** [comment]
Jo, ale není to v interfacu spodního dílu. Never mind, z praktického hlediska s tebou souhlasím na 100 %. Nemám čas to udělat dřív než v pátek.

**Comment by syky27** [comment]
ok

--
Tomas Sykora
