### ISSUE TITLE
Vyjasneni rozmeru

### ISSUE THREAD

**Issue by marekreimer** [3DprintFIT/B171HW-TabletBarMount-Assignment#13]
@syky27 @hroncok 
Uz jsem to konecne dodelal a prisel jsem na nejasnost u dvou rozmeru.
1. Hloubka diry na hlavu sroubu (screw_head_depth)
2. Stred naklapeni spodniho casti drzaku (raiser_inlet_top_thickness)

Udelal jsem to podle prvniho prilozeneho obrazku.
Dira na hlavicku sroubu mi takhle dava smysl, protoze to zarucuje, ze hlavicka nebude vycuhovat do prostoru pro tablet, ale pri nekterych konfiguracich se muze stat ze dira projde skrz vsechen material a nezbude co prisroubovat.
Mam tohle resit, pokud ano tak jak je spravne reseni?

Stred naklapeni jsem umistil podle obrazku v zadani do vysky raiser_depth + raiser_inlet_top_thickness ale tim vznika problem kdy se pri vyssich uhlech naklopeni dira na predstavec prorizne podlozkou na tablet jako je to na druhem obrazku. Moje otazka tedy je jestli to tak mam nechat byt, nebo jestli to osetrit tak aby raiser_inlet_top_thickness byla minimalni tloustka materialu mezi predstavcem a tabletem?

![dims](https://user-images.githubusercontent.com/32454894/32983356-76492c02-cc93-11e7-824f-3fbbecac411d.PNG)

![hole](https://user-images.githubusercontent.com/32454894/32983443-fbebedee-cc94-11e7-884e-806c6808302b.png)

**Comment by syky27** [comment]
Ahoj mas to spravne, bude zaruceno, ze hodnoty budou zadany tak aby to slo realne vytisknout.

**Comment by hroncok** [comment]
Úplně správně to nemáš. @syky27 říká pravdu: zaručeno to bude. Ale zanoření šroubu se měří podle neotočeného držáku, viz https://github.com/3DprintFIT/B171HW-Assignment/blob/master/assets/holder_cut_rotated.png, který se to snaží ukázat.

![](https://github.com/3DprintFIT/B171HW-Assignment/raw/master/assets/holder_cut_rotated.png)

**Comment by syky27** [comment]
To mi uniklo, pardon
--
Tomas Sykora

**Comment by marekreimer** [comment]
Aha, to jsem z toho obrazku nepochopil. diky za pripominku. Potom mam teda otazku jestli timhle pristupem nemuze nastat situace, ze hlavicka sroubu nebude plne zanorena do diry? Nebo je proste na uzivateli aby si tam dal takovou hloubku, ze bude plne zanorena?

**Comment by syky27** [comment]
To je na uzivateli, muze to nastat, nechceme aby jsi to nijak osetroval

**Comment by marekreimer** [comment]
Ok, diky

**Comment by hroncok** [comment]
Zkusím k tomu obrázku dát popisek. Co třeba takhle:

> Všimněte si, že hlavičky šroubů jsou zanořené podle neotočeného modelu (znázorněného zde pomocí OpenSCAD modifikátoru `%`). Je na uživateli modulu, aby v případě natočení zvolil vhodnou hloubku zanoření tak, aby šrouby nepřekážely. Nesnažte se šrouby zanořovat kvůli naklopení více (či snad méně).

**Comment by syky27** [comment]
👌

**Comment by berusjan** [comment]
Já pořád nejsem schopná pochopit, jak je to při naklonění tabletu s raiser_inlet_top_thickness. Mám hotový model, když je tablet rovně, ale není mi přesně jasné, které strany se prodlužují/zkracují při naklonění. Má být tloušťka raiser_inlet_top_thickness stále stejná a měnit se budou jen její stěny? (Myslím to tak, že by horní stěna představce rotovala s držákem.) Nebo mám prostě vypnit vzniklou mezeru jakoby byla součástí horní stěny? (S tím, že na druhé straně by se tloušťka zmenšovala.)

**Comment by hroncok** [comment]
raiser_inlet_top_thickness platí na středu modelu podle Y. Horní stěna představce nerotuje. Pouze vyplníš vniklou mezeru nahoře (a vyřízneš vzniklou překážku dole).
