### ISSUE TITLE
Test 18

### ISSUE THREAD

**Issue by ctrnama2** [3DprintFIT/B171HW-TabletBarMount-Assignment#16]
V zadání je uvedeno že "Můžete předpokládat, že raiser_width < raiser_height" 

Avšak v testu číslo 18 se nejprve inicializují proměnné:
raiser_width=20;
raiser_height=40;

A poté se renderuje bottom_part s:
raiser_width=raiser_width*2,
raiser_height=raiser_height/2,

což podle mě nesplňuje podmínku zadání.

**Comment by hroncok** [comment]
Upraveno na:

```diff
-                raiser_height=raiser_height/2,
+                raiser_height=raiser_height*1.5,
```

BTW ani naše řešení pro původní hodnoty nefungovalo, jen jsem si toho nevšiml.
