### ISSUE TITLE
Otočení top_part

### ISSUE THREAD

**Issue by ctrnama2** [3DprintFIT/B171HW-TabletBarMount-Assignment#17]
V zadání je uvedeno že
"Samostatně použitý top_part leží na podložce (z = 0), vystředěn podle os x a y
displayem vzhůru, **dírami na kabely po směru osy Y**"

Což já osobně chápu tak, že dívám-li se dírami na kabely skrz model tak se dívám ve směru osy Y. Což ale nerespektuje žádný z testů a i v celém držáku je top part použitý tak, že je vždy díra na kabely rovnoběžná s osou X.

Možná jen chápu špatně co znamená **dírami na kabely po směru osy Y**.

**Comment by hroncok** [comment]
Zkontroluju.

**Comment by hroncok** [comment]
Ano, to je chyba v zadání. Má to být podle X, stejně jako když je použitý dohromady. Omlouvám se.
