### ISSUE TITLE
Hodnota $fn

### ISSUE THREAD

**Issue by ctrnama2** [3DprintFIT/B171HW-TabletBarMount-Assignment#18]
V případě použití "circle(d=nut_diameter, $fn=6)" pro vytvoření šestihranné matice hlásí tester "Forbidden fruits!"

**Comment by hroncok** [comment]
Rozumím. Detekoval jsem naivně jen cylindr.

**Comment by ctrnama2** [comment]
Myslel jsem si to ale předpokládal jsem, že nebudu jediný a není nutné generovat matici cylindrem.

**Comment by hroncok** [comment]
Samozřejmě. Hotovo.
