### ISSUE TITLE
TEST 07

### ISSUE THREAD

**Issue by hiimnit** [3DprintFIT/B171HW-TabletBarMount-Assignment#19]
Reference v 7. testu nema zaoblene rohy, podle popisku bych cekal zaoblene?
> Should be same as default values 

Reference:
![image](https://user-images.githubusercontent.com/16312663/33239768-65efaebe-d2a9-11e7-80cc-1ccf2ba480fe.png)
Me reseni:
![image](https://user-images.githubusercontent.com/16312663/33239781-aa9409b6-d2a9-11e7-8f28-6d0e863f5a3f.png)
+ zbyle testy mi vychazi v poradku

**Comment by hroncok** [comment]
To je issue v OpenSCADu, zkusím to nějak workaroundovat. https://github.com/openscad/openscad/issues/999
