### ISSUE TITLE
screw_spacing

### ISSUE THREAD

**Issue by AndreyDenissyuk** [3DprintFIT/B171HW-TabletBarMount-Assignment#21]
module bottom_part:
"screw_spacing je rozteč po ose Y"
je to roztec mezi dirami nebo mezi jejich stredy?

**Comment by hroncok** [comment]
Středy. Pošleš prosím pull request s upřesněním? Nejsem u počítače.

**Comment by AndreyDenissyuk** [comment]
done

**Comment by hroncok** [comment]
thanks
