### ISSUE TITLE
Test 17, 18 - šrouby do představce

### ISSUE THREAD

**Issue by martilad** [3DprintFIT/B171HW-TabletBarMount-Assignment#25]
V zadání jsou inicializovány hodnoty pro průměr a jeho hlavičku takové: 
screw_diameter=4; 
screw_head_diameter=6; 

Ty jsou pak změněny: 
screw_diameter=screw_diameter * 2, // v testu 17 je * 3
screw_head_diameter=screw_head_diameter,

Ale to vychází že je hlavička šroubu menší než jeho průměr, což si moc nedokážu představit. Jestli to lze řešit jako je to v ukázkovém řešení, kde mi připadá že je díra udělána podle screw_diameter a menší screw_head_diameter je zanedbaný?

**Comment by hroncok** [comment]
Pokud to tak je, tak to nemusíš řešit a v případě chyby to uznáme jako naší chybu.

**Comment by martilad** [comment]
dobře děkuji
