### ISSUE TITLE
Jak fungují posuny?

### ISSUE THREAD

**Issue by hroncok** [3DprintFIT/B171HW-TabletBarMount-Assignment#4]
Ze zadání jsem to úplně nepochopil. V jakém pořadí se třeba držák naklápí/posouvá?

**Comment by syky27** [comment]
No to neni jeste zadefinovany, nejak jsem vcera uz nebyl schopen vymyslet jak to popsat cesky...

**Comment by hroncok** [comment]
ok

**Comment by syky27** [comment]
respektive na posun je 
```
holder_position_x,
holder_position_y,
```

Asi chybi promena na rotaci, pozorovaciho uhlu
