### ISSUE TITLE
Pozice v 3D prostoru

### ISSUE THREAD

**Issue by hroncok** [3DprintFIT/B171HW-TabletBarMount-Assignment#5]
Aby se to dalo lépe testovat, chceme aby všichni dávaly svůj model na konkrétní místo. Navrhuji to určit tak, že celý model musí stát na podložce a a je to centrované podle představců. Řídítka jsou rovnoběžná s osou X, nebo tak něco.

**Comment by syky27** [comment]
Souhlasím, klidně to muzes zformalizovat, nebo tohle podle me nekde uz mame z minulych let zformalizovane.

**Comment by hroncok** [comment]
Už to tam je.
